services:
  postgres:
    container_name: postgres_container_test
    image: postgres
    environment:
      POSTGRES_USER: keerk99
      POSTGRES_PASSWORD: keerk99
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - ecommerce-network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container_test
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - ecommerce-network
    restart: unless-stopped
  mongodb:
    container_name: mongodb_container_test
    image: mongo:6.0
    hostname: host-mongo
    environment:
      MONGO_INIT DB_ROOT_USERNAME: keerk99
      MONGO_INIT DB_ROOT_PASSWORD: keerk99
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    networks:
      - ecommerce-network
    restart: unless-stopped
  mongo-express:
    container_name: mongo_express_container_test
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMIN USERNAME: keerk99
      ME_CONFIG_MONGODB_ADMIN PASSWORD: keerk99
      ME_CONFIG_MONGODB_SERVER: mongodb_container_test
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network
    restart: unless-stopped
    depends_on:
      - mongodb

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
